highlighter: "rouge"
# - markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap

title: "Brandon Bohling"
tagline: ""
description: "Follow <a href=\"https://micro.blog/bbohling\">@bbohling on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/bbohling\">@bbohling on Micro.blog</a>."
baseurl: ""
url: "https://micro.brandonbohling.com"
markdown: "kramdown"
username: "bbohling"
microblog_user: "bbohling"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Brandon Bohling"
name: "Brandon Bohling"
gravatar_hash: "93a505b040d765a20c04134f19dbd9e3"
avatar: "https://micro.blog/bbohling/avatar.jpg"
full_name: "Brandon Bohling"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "691"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Brandon Bohling"
podcast: false